Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

Conectado correctamente

Cargar Dataset

In [4]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"
siniestros = pd.read_csv(url)

Exploración de datos

In [5]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [6]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

In [7]:
siniestros.isnull().sum()

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [8]:
siniestros.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [9]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [10]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [11]:
siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates()

Funciones especificas

In [12]:
#Normalización de estado

map_estado = {
    "RECHAZADO": "Rechazado",
    "rechazado": "Rechazado",
    "ABIERTO": "Abierto",
    "abierto": "Abierto",
    "CERRADO": "Cerrado",
    "cerrado": "Cerrado",
}

siniestros["estado"] = (
    siniestros["estado"]
    .astype(str)
    .str.strip()
    .replace(map_estado)
)

siniestros["monto_siniestro"] = (

   siniestros["monto_siniestro"]
   .astype(str)
   .str.replace(",",".",regex=False)
)

#Convertir decimal
siniestros["monto_siniestro"] = pd.to_numeric(
    siniestros["monto_siniestro"],
    errors="coerce"
)


#Un solo formato para fecha
siniestros["fecha_siniestro"] = (
  siniestros["fecha_siniestro"]
  .astype(str)
  .str.replace("-","/",regex=False)
)

#Convertir a DateTime fecha_siniestro
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    dayfirst=True
)

In [13]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  1813 non-null   datetime64[ns]
 3   monto_siniestro  1976 non-null   float64
 4   estado           4620 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 180.6+ KB

In [14]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    Abierto
1             2       2465      2025-08-01              NaN    Abierto
2             3      15785      2025-09-19           702.27    Cerrado
3             4      14299      2025-09-27           274.63    Abierto
4             5      12908      2025-12-01              NaN  Rechazado

Separar validos y rechazados

In [15]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. no debe haber espacios vcios en monto_siniestro ni en estado

columnas_obligatorias = [
    "id_siniestro",
    "id_poliza",
    "fecha_siniestro",
    "monto_siniestro",
    "estado"
]

condicion_nulos = siniestros[columnas_obligatorias].isna().any(axis=1)

condicion_monto_invalido = siniestros["monto_siniestro"] <= 0

condicion_rechazo = condicion_nulos | condicion_monto_invalido

rechazados = siniestros.loc[condicion_rechazo].copy()
validos = siniestros.loc[~condicion_rechazo].copy()

Motivo del rechazo

In [16]:
from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_siniestro"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["id_poliza"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["fecha_siniestro"]):
    motivos.append("fecha_nula_o_invalida")

  if pd.isna(row["estado"]):
    motivos.append("estado_no_valido")

  if pd.isna(row["monto_siniestro"]):
    motivos.append("monto_siniestro_no_valido")

  elif row["monto_siniestro"] < 0:
      motivos.append("monto_siniestro_invalido")

  return ",".join(motivos)

Agregar motivo de rechazo

In [17]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [18]:
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [19]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    Abierto
1             2       2465      2025-08-01              NaN    Abierto
2             3      15785      2025-09-19           702.27    Cerrado
3             4      14299      2025-09-27           274.63    Abierto
4             5      12908      2025-12-01              NaN  Rechazado

In [20]:
siniestros.dtypes

id_siniestro                int64
id_poliza                   int64
fecha_siniestro    datetime64[ns]
monto_siniestro           float64
estado                     object
dtype: object

In [21]:
siniestros.isnull().sum()

id_siniestro          0
id_poliza             0
fecha_siniestro    2807
monto_siniestro    2644
estado                0
dtype: int64

In [22]:
siniestros.value_counts()

id_siniestro  id_poliza  fecha_siniestro  monto_siniestro  estado
4620          10815      2025-10-11       14958.46         Abierto      1
1             17400      2025-10-16       2092.59          Abierto      1
3             15785      2025-09-19       702.27           Cerrado      1
4             14299      2025-09-27       274.63           Abierto      1
8             23824      2025-01-17       2736.20          Abierto      1
                                                                       ..
45            15100      2025-01-27       8761.24          Abierto      1
36            16929      2025-01-06       3649.94          Cerrado      1
33            2231       2025-09-21       2443.90          Rechazado    1
27            22625      2025-03-07       141.77           nan          1
25            719        2025-12-25       3257.92          nan          1
Name: count, Length: 791, dtype: int64

In [23]:
validos.to_sql(
    "siniestros",
    engine,
    if_exists="append",
    index=False
  )

784

Validar Carga

In [24]:
pd.read_sql(
    "Select * From siniestros Limit 100",
    engine
)

    id_siniestro  id_poliza fecha_siniestro  monto_siniestro   estado
0              1      17400      2025-10-16          2092.59  Abierto
1              3      15785      2025-09-19           702.27  Cerrado
2              4      14299      2025-09-27           274.63  Abierto
3              8      23824      2025-01-17          2736.20  Abierto
4             22       6924      2025-11-16         10436.86  Cerrado
..           ...        ...             ...              ...      ...
95           519       2775      2025-09-20         11906.59  Abierto
96           523       2414      2025-08-10         13565.60  Abierto
97           526       6685      2026-01-27           965.71  Cerrado
98           530      19258      2025-10-10         14448.22  Abierto
99           535      17558      2025-05-11           775.73  Cerrado

[100 rows x 5 columns]