Importar Librerias

In [3]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [4]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 66.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [5]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

Conectado correctamente

Cargar Dataset

In [6]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url)

Exploración de datos

In [7]:
aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [8]:
aseguradoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

In [9]:
aseguradoras.isnull().sum()

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [10]:
aseguradoras.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [11]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [12]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [13]:
aseguradoras = normalizar_columnas(aseguradoras)
aseguradoras = limpiar_texto(aseguradoras)
aseguradoras = aseguradoras.drop_duplicates()

Funciones especificas

In [14]:
#Normalización de pais

map_pais = {
    "elsalvador": "El Salvador",
    "el salvador": "El Salvador",
    "costa rica": "Costa Rica"
}

aseguradoras["pais"] = (
    aseguradoras["pais"]
    .str.lower()
    .replace(map_pais)
)

#Estandarizar raiting

map_rating = {
    "alto": "Alto",
    "a": "Alto",
    "medio": "Medio",
    "m": "Medio",
    "bajo": "Bajo",
    "b": "Bajo"
}

aseguradoras["rating_riesgo"] = (
    aseguradoras["rating_riesgo"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace(map_rating)
    )

aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")


valores_validos = ["Alto", "Medio", "Bajo"]

aseguradoras.loc[
    ~aseguradoras["rating_riesgo"].isin(valores_validos),
    "rating_riesgo"] = np.nan
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.title()

In [15]:
aseguradoras.head()

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No Especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5  El Salvador             Bajo

In [16]:
aseguradoras["rating_riesgo"].value_counts(dropna=False)

rating_riesgo
Bajo               5
Alto               4
No Especificado    4
Medio              2
Name: count, dtype: int64

Separar Validos y rechazados

In [17]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2 el nombre debe ser not null

validos = aseguradoras[
    aseguradoras["id_aseguradora"].notna() &
    aseguradoras["nombre"].notna()
].copy()

rechazados = aseguradoras [
    ~aseguradoras["id_aseguradora"].isna() |
    ~aseguradoras["nombre"].isna()
]

Motivo del rechazo

In [18]:
def motivo(row):

  motivos = []

  if pd.isna(row["id_aseguradora"]):
    motivos.append("Id_no_valido")

    if pd.isna(row["nombre"]):
      motivos.append("Nombre_no_valido")

    return ",".join(motivos)

    rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [19]:
validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

Cargar datos en PostgreSQL

In [20]:
validos.to_sql(
    "aseguradoras",
    engine,
    if_exists="append",
    index=False
  )

15

Validar Carga

In [21]:
pd.read_sql(
    "Select * From aseguradoras Limit 100",
    engine
)

    id_aseguradora          nombre             pais    rating_riesgo
0                1   Aseguradora 1       Costa Rica             Alto
1                2   Aseguradora 2      El Salvador             Bajo
2                3   Aseguradora 3      El Salvador  No Especificado
3                4   Aseguradora 4       Costa Rica            Medio
4                5   Aseguradora 5      El Salvador             Bajo
5                6   Aseguradora 6  No especificado            Medio
6                7   Aseguradora 7        guatemala             Alto
7                8   Aseguradora 8           panamá             Bajo
8                9   Aseguradora 9  No especificado             Bajo
9               10  Aseguradora 10           panamá  No Especificado
10              11  Aseguradora 11         honduras  No Especificado
11              12  Aseguradora 12      El Salvador             Bajo
12              13  Aseguradora 13         honduras             Alto
13              14  Aseguradora 14      El Salvador  No Especificado
14              15  Aseguradora 15      El Salvador             Alto