Importar Librerias

In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

Conectado correctamente

Cargar Dataset

In [4]:
url_tipos = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"
tipos_seguro = pd.read_csv(url_tipos)
tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

Exploración de datos

In [5]:
tipos_seguro.shape

(12, 4)

In [6]:
tipos_seguro.columns

Index(['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base'], dtype='object')

In [7]:
tipos_seguro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

In [8]:
tipos_seguro.isnull().sum()

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

Normalizar nombres de columnas (Estandarización de esquemas)

In [9]:
tipos_seguro.columns= (
    tipos_seguro.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

Limpieza de texto

Reglas:

1.   id_tipo_seguro no puede ser nulo
2.   tipo no puede ser nulo

In [10]:
for col in tipos_seguro.select_dtypes(include="object").columns:
  tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()
  tipos_seguro[col] = tipos_seguro[col].replace(
      ["nan","None","NULL", "null",""],
      pd.NA
  )

  validos = tipos_seguro[
      tipos_seguro["id_tipo_seguro"].notna() &
      tipos_seguro["tipo"].notna()
  ].copy()

  rechazados = tipos_seguro[
      tipos_seguro["id_tipo_seguro"].isna() |
      tipos_seguro["tipo"].isna()
  ].copy()

Motivo de rechazo

In [11]:
def motivo(row):
  motivos=[]

  if pd.isna(row['id_tipo_seguro']):
    motivos.append("id_vacio")

  if pd.isna(row['tipo']):
    motivos.append("tipo_vacio")

    return ",".join(motivos)

Aplicar funcion

In [12]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Eliminar Duplicados

In [13]:
tipos_seguro = tipos_seguro.drop_duplicates()

Transformación de texto

In [14]:
tipos_seguro["tipo"] = tipos_seguro["tipo"].str.title()
tipos_seguro["categoria"] = tipos_seguro["categoria"].str.title()

Reemplazar categoria vacia

In [15]:
tipos_seguro["categoria"] = tipos_seguro["categoria"].fillna("No especificado")

Limpiar Números

In [16]:
tipos_seguro["riesgo_base"] = tipos_seguro["riesgo_base"].replace("-", np.nan)

tipos_seguro["riesgo_base"] = pd.to_numeric(
    tipos_seguro["riesgo_base"], errors="coerce"
)

Exportación de dataset limpio

In [17]:
tipos_seguro.to_csv(
    "tipos_seguro_curated.csv",
    index = False
)

Exportar dataset de rechazos

In [18]:
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

Conectar con PostgreSQL

In [19]:
#Instalamos librerias
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

Conexión

In [20]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

Cargar datos a PostgreSQL

In [21]:
tipos_seguro.to_sql(
    "tipos_seguro",
    engine,
    if_exists="append",
    index=False
)

12

Validar que se cargó

In [22]:
pd.read_sql(
    "Select * from tipos_seguro LIMIT 10",
    engine
)

   id_tipo_seguro        tipo        categoria  riesgo_base
0               1        Pyme         Familiar          NaN
1               2  Industrial      Empresarial         4.68
2               3  Industrial         Familiar         5.10
3               4  Industrial         Personal          NaN
4               5        Auto      Empresarial         9.07
5               6  Industrial      Empresarial         2.52
6               7       Salud         Personal         0.92
7               8   Educación      Empresarial         7.42
8               9  Accidentes  No especificado         5.68
9              10      Dental         Especial         2.70